### ISSUE TITLE
Blur incompatibility with 21w16a - 2.1.0

### ISSUE THREAD

**Issue by triphora** [Motschen/Blur#14]
Evening,
I crash when loading Blur on 21w16a, with 2.1.0, made for 21w08b. It appears to conflict with fabric-renderer-indigo (Fabric API). The game crashes citing Indigo as the problem, but I find this unlikely; FAPI is more likely to be tested than Blur built against an old snapshot version (no offense).

<details><summary>Crash Report</summary><pre>
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 27/04/21 8:43 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'fabric-renderer-indigo'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:442)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_1921.<clinit>(class_1921.java:47)
	at net.fabricmc.fabric.api.renderer.v1.material.BlendMode.<clinit>(BlendMode.java:33)
	at net.fabricmc.fabric.impl.client.indigo.renderer.R<enderMaterialImpl.<clinit>(RenderMaterialImpl.java:34)
	at net.fabricmc.fabric.impl.client.indigo.renderer.IndigoRenderer.materialFinder(IndigoRenderer.java:54)
	at net.fabricmc.fabric.impl.client.indigo.renderer.IndigoRenderer.<clinit>(IndigoRenderer.java:37)
	at net.fabricmc.fabric.impl.client.indigo.Indigo.onInitializeClient(Indigo.java:137)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.satin.client.json:render.MultiPhaseParametersAccessor] from phase [DEFAULT] in config [mixins.satin.client.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 24 more
Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching field_21406:Lnet/minecraft/class_4668$class_4683; in net/minecraft/class_1921$class_4688 for mixins.satin.client.json:render.MultiPhaseParametersAccessor->@Accessor[FIELD_GETTER]::getTexture()Lnet/minecraft/class_4668$class_4683; [INJECT Applicator Phase -> mixins.satin.client.json:render.MultiPhaseParametersAccessor -> Apply Accessors ->  -> Locate -> mixins.satin.client.json:render.MultiPhaseParametersAccessor->@Accessor[FIELD_GETTER]::getTexture()Lnet/minecraft/class_4668$class_4683;]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:518)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:501)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:475)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1318)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1051)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 24 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:442)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 21w16a
	Minecraft Version ID: 21w16a
	Operating System: Linux (amd64) version 5.12.0-rc8-1-mainline
	Java Version: 1.8.0_202, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3571009208 bytes (3405 MB) / 4294967296 bytes (4096 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 8
	JVM Flags: 9 total; -Xss1M -XX:+UseG1GC -Xmx5G -Xms512M -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=25 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		blur: Blur (Fabric) 2.1.0
		fabric: Fabric API 0.33.3+1.17
		fabric-api-base: Fabric API Base 0.2.2+23b3c92ed1
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.2+413ddf64d1
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.8+413ddf64d1
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+92519afad1
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+bb687600d1
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afad1
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+41a68552d1
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+23b3c92ed1
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+92519afad1
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.9+14efdf6ed1
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+92519afad1
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.8+d748de6cd1
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afad1
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+92519afad1
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+23b3c92ed1
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+12865e78d1
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+524a2e85d1
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3ed1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+23b3c92ed1
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+92519afad1
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afad1
		fabric-models-v0: Fabric Models (v0) 0.3.0+ecfd213cd1
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.7+413ddf64d1
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+413ddf64d1
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afad1
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.5+40e100ebd1
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+92519afad1
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+92519afad1
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.8+413ddf64d1
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+12865e78d1
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+413ddf64d1
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+12865e78d1
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+92519afad1
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+92519afad1
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afad1
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+12865e78d1
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+12865e78d1
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.1+41a68552d1
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+23b3c92ed1
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.8+23b3c92ed1
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.3+41a68552d1
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+92519afad1
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.10+f5d458fcd1
		fabricloader: Fabric Loader 0.11.3
		java: Java HotSpot(TM) 64-Bit Server VM 8
		minecraft: Minecraft 1.17-alpha.21.16.a
		satin: Satin 1.6.0-nightly.20w48a
	Launched Version: fabric-loader-0.11.3-21w16a
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: Using framebuffer using OpenGL 3.2
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: \<unknown\>
</pre></details>

**Comment by Motschen** [comment]
Yeah, the mod doesn't work on the latest snapshots since a lot of shader stuff changed.
