### ISSUE TITLE
Incompatibility with Tweakmyclient

### ISSUE THREAD

**Issue by boasbakker** [Motschen/Blur#19]
Minecraft crashed when using both

**Comment by boasbakker** [comment]
[15:50:05] [Render thread/WARN]: @ModifyConstant conflict. Skipping mixins.blur.json:MixinScreen->@ModifyConstant::getFirstBackgroundColor(I)I with priority 1000, already redirected by mixins.TweakMyClient.json:MixinScreen->@ModifyConstant::customStartColor(I)I with priority 1000
[15:50:05] [Render thread/WARN]: @ModifyConstant conflict. Skipping mixins.blur.json:MixinScreen->@ModifyConstant::getSecondBackgroundColor(I)I with priority 1000, already redirected by mixins.TweakMyClient.json:MixinScreen->@ModifyConstant::customStopColor(I)I with priority 1000
[15:50:05] [Render thread/WARN]: @ModifyConstant conflict. Skipping mixins.blur.json:MixinScreen->@ModifyConstant::getFirstBackgroundColor(I)I with priority 1000, already redirected by mixins.TweakMyClient.json:MixinScreen->@ModifyConstant::customStartColor(I)I with priority 1000
[15:50:05] [Render thread/WARN]: @ModifyConstant conflict. Skipping mixins.blur.json:MixinScreen->@ModifyConstant::getSecondBackgroundColor(I)I with priority 1000, already redirected by mixins.TweakMyClient.json:MixinScreen->@ModifyConstant::customStopColor(I)I with priority 1000
[15:50:05] [Render thread/INFO]: [STDERR]: Failed to start Minecraft:
[15:50:05] [Render thread/INFO]: [STDERR]: java.lang.reflect.InvocationTargetException
[15:50:05] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[15:50:05] [Render thread/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[15:50:05] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:236)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
[15:50:05] [Render thread/INFO]: [STDERR]: 	... 8 more
[15:50:05] [Render thread/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[15:50:05] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
[15:50:05] [Render thread/INFO]: [STDERR]: 	... 10 more
[15:50:05] [Render thread/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[15:50:05] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:187)
[15:50:05] [Render thread/INFO]: [STDERR]: 	... 15 more
[15:50:05] [Render thread/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method getFirstBackgroundColor(I)I in mixins.blur.json:MixinScreen failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Blur-refmap.json
[15:50:05] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[15:50:05] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[15:50:05] [Render thread/INFO]: [STDERR]: 	... 22 more

**Comment by tort-oise** [comment]
This issue page is practically dead, but to give you an reply: This is entirely on TweakMyClient's end. Plus, TweakMyClient is such a small mod, standing at only ~600 downloads. It also seems to have compatibility issues with Xaero's Mini/World map.
I recommend you go to TweakMyClient's GitHub (https://github.com/Hendrix-Shen/Tweak-My-Client) instead, and post an issue there about it, as there's practically nothing on this end.

**Comment by boasbakker** [comment]
For me it works with xaeros world map btw.
I'll report this at tweakmyclient

**Comment by tort-oise** [comment]
Yeah, it works with worldmap for me as well. Just not minimap, I guess.

**Comment by tort-oise** [comment]
Also, please close this issue, as the bug is resolved. However, there's not an available release with the bugfix available for download, so please wait until TweakMyClient releases a fixed version. Thanks.

**Comment by boasbakker** [comment]
Ok
