### ISSUE TITLE
Disabling midnightlib's hats seems to prevent the game from loading worlds

### ISSUE THREAD

**Issue by BurntKrispe** [Motschen/Blur#30]
Stacktrace:
	at eu.midnightdust.hats.witch.WitchHatFeatureRenderer.render(WitchHatFeatureRenderer.java:60)
	at eu.midnightdust.hats.witch.WitchHatFeatureRenderer.method_4199(WitchHatFeatureRenderer.java:28)
Edit: The embedded version of MidnightLib.

**Comment by Motschen** [comment]
The embedded version of MidnightLib is pretty old, please put the newest version of MidnightLib in your mod folder alongside Blur, it should be fixed there. https://modrinth.com/mod/midnightlib/version/kU3LjFF9

**Comment by Motschen** [comment]
The newest version of MidnightLib is now shipped with the latest release of Blur :)
