### ISSUE TITLE
booting up blur-2.4.0 on snapshot version 21w42a and get this error

### ISSUE THREAD

**Issue by JoostGames23** [Motschen/Blur#32]
Just as the title says, I get this crash report while booting up my usual modded snapshot: 

## Crash Report
```
---- Minecraft Crash Report ----
// My bad.

Time: 11/7/21, 5:09 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'blur'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.<init>(class_310.java:460)
	at net.minecraft.client.main.Main.main(Main.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.NoClassDefFoundError: ladysnake/satin/api/managed/ShaderEffectManager
	at com.tterrag.blur.Blur.<init>(Blur.java:25)
	at com.tterrag.blur.Blur.<clinit>(Blur.java:29)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.lambda$getOrCreate$0(EntrypointStorage.java:106)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:104)
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:191)
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
Caused by: java.lang.ClassNotFoundException: ladysnake.satin.api.managed.ShaderEffectManager
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 22 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.<init>(class_310.java:460)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22494.1000 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22494.1000 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22494.1000 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22494.1000 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22494.1000 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.2110.6 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22494.1000 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		OleAut32.dll:OLEAUT32.DLL:10.0.22494.1000 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.22494.1000 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.22492.1000 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.28.29913.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22494.1000 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22494.1000 (WinBuild.160101.0800):Microsoft Corporation
		apphelp.dll:Application Compatibility Client Library:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		awt.dll:OpenJDK Platform binary:16.0.1.0:Microsoft
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22494.1000 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22494.1000 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client Service:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 Client:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.22494.1000 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll
		java.dll:OpenJDK Platform binary:16.0.1.0:Microsoft
		javaw.exe:OpenJDK Platform binary:16.0.1.0:Microsoft
		jimage.dll:OpenJDK Platform binary:16.0.1.0:Microsoft
		jli.dll:OpenJDK Platform binary:16.0.1.0:Microsoft
		jna1391180461752511561.dll:JNA native library:6.1.1:Java(TM) Native Access (JNA)
		jvm.dll:OpenJDK 64-Bit server VM:16.0.1.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.22494.1000 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:OpenJDK Platform binary:16.0.1.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:16.0.1.0:Microsoft
		msvcp140.dll:Microsoft® C Runtime Library:14.28.29913.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22494.1000 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.22494.1000 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:16.0.1.0:Microsoft
		nio.dll:OpenJDK Platform binary:16.0.1.0:Microsoft
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22494.1000 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:NT Layer DLL:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows System Performance Objects DLL:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.22494.1000 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.22494.1000 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22494.1000 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:16.0.1.0:Microsoft
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22494.1000 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.28.29913.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:16.0.1.0:Microsoft
		win32u.dll:Win32u:10.0.22494.1000 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.22494.1000 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:Windows Base Types DLL:10.0.22499.1000 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.22494.1000 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:16.0.1.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 21w42a
	Minecraft Version ID: 21w42a
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 343897920 bytes (327 MiB) / 603979776 bytes (576 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600X 6-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1650 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2187
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7247
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 30646.23
	Virtual memory used (MB): 11955.45
	Swap memory total (MB): 14336.00
	Swap memory used (MB): 132.46
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin mc1.17-2.1.1
		autofish: Autofish 0.9.3
		blur: Blur (Fabric) 2.4.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config: Cloth Config v6 6.0.39
		dark-loading-screen: Dark Loading Screen 1.6.11
		fabric: Fabric API 0.41.2+1.18
		fabric-api-base: Fabric API Base 0.3.0+a02b446388
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+0b94475288
		fabric-biome-api-v1: Fabric Biome API (v1) 5.0.1+0b94475288
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446388
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c88
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa88
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931888
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931888
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31088
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.2+0b94475288
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.1+938d6de088
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.12+dc3d5c4788
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa88
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931888
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+cbda931888
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612188
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+cbda93184c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e88
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.6+d1937ce488
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446388
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa88
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446388
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+6eb8b35a88
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa88
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+cbda931888
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446388
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+938d6de088
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.1+01912dd288
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.6+dc3d5c4788
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.9+0b94475288
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.4+c683a65588
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.2.0+8f2c3e044c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223088
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.5+c683a65588
		fabric-rendering-v1: Fabric Rendering (v1) 1.9.0+c683a65588
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b4c
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+cbda931888
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931888
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.2+6eb8b35a88
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.2+8f2c3e0488
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446388
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612188
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.4.1+0b94475288
		fabricloader: Fabric Loader 0.11.7
		fallingleaves: Falling Leaves 1.7.4+1.17.1
		fiber: fiber 0.23.0-2
		iris: Iris 1.1.3-pre+rev.c347131-dirty
		java: OpenJDK 64-Bit Server VM 16
		lambdynlights: LambDynamicLights 2.0.2+1.17
		lazydfu: LazyDFU 0.1.2
		libzoomer: LibZoomer 0.2.1+1.17
		midnightlib: MidnightLib 0.3.0
		minecraft: Minecraft 1.18-alpha.21.42.a
		modmenu: Mod Menu 3.0.0
		no_fog: No Fog 1.1.0+1.17.1
		okzoomer: Ok Zoomer 5.0.0-beta.2+1.17
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		sodium: Sodium 0.3.2+IRIS243-rev.470759f-dirty
		spruceui: SpruceUI 3.2.0+1.17
		voicechat: Simple Voice Chat 21w43a-1.0.0
	Launched Version: fabric-loader-0.11.7-21w42a
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
```

What causes this issue and how to fix it?

**Comment by Motschen** [comment]
Blur is not compatible with 1.18 snapshots yet, due to a library it depends on not being updated.

**Comment by JoostGames23** [comment]
Then why is this on your curseforge page? If it's not ready yet for usage due to a lib needing to update.
![image](https://user-images.githubusercontent.com/61411999/140801114-59383de1-3ed9-4071-ac82-db1fd3d38cb8.png)

**Comment by Motschen** [comment]
Oh, it was a mistake, sorry
